import { table } from './src/core/api.mjs';
import { toCsv } from './src/core/export.mjs';

const app=document.querySelector('#app');
let currentRows=[];
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function show(t,type='success'){const e=document.querySelector('#flash');if(e)e.innerHTML=`<p class="${type}">${esc(t)}</p>`;}

function shell(){return `<section class="card audit-tool"><h2>Búsqueda y exportación de auditoría</h2><form id="audit-search" class="form two"><div class="field"><label>Actor UUID</label><input name="actor"></div><div class="field"><label>Acción contiene</label><input name="action" placeholder="route.publish"></div><div class="field"><label>Tipo de entidad</label><input name="entity_type" placeholder="routes"></div><div class="field"><label>Desde</label><input name="from" type="datetime-local"></div><button class="btn primary">Buscar</button><div class="toolbar"><button id="audit-csv" type="button" class="btn secondary">Exportar CSV</button><button id="audit-json" type="button" class="btn secondary">Exportar JSON</button></div></form><div id="audit-search-results"></div></section>`;}

function queryFor(form){const parts=['select=id,actor_user_id,action,entity_type,entity_id,before_data,after_data,created_at','order=created_at.desc','limit=1000'];const actor=form.elements.actor.value.trim();const action=form.elements.action.value.trim();const entity=form.elements.entity_type.value.trim();const from=form.elements.from.value;if(actor)parts.push(`actor_user_id=eq.${encodeURIComponent(actor)}`);if(action)parts.push(`action=ilike.${encodeURIComponent(`*${action}*`)}`);if(entity)parts.push(`entity_type=eq.${encodeURIComponent(entity)}`);if(from)parts.push(`created_at=gte.${encodeURIComponent(new Date(from).toISOString())}`);return `?${parts.join('&')}`;}

function render(){const target=document.querySelector('#audit-search-results');if(!target)return;if(!currentRows.length){target.innerHTML='<p class="muted">Sin resultados.</p>';return;}target.innerHTML=`<p class="muted">${currentRows.length} eventos</p><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Actor</th><th>Acción</th><th>Entidad</th><th>Cambio</th></tr></thead><tbody>${currentRows.map(r=>`<tr><td>${esc(r.created_at)}</td><td class="code">${esc(r.actor_user_id||'sistema')}</td><td>${esc(r.action)}</td><td>${esc(r.entity_type)}<br><span class="code">${esc(r.entity_id||'')}</span></td><td><details><summary>ver</summary><pre class="code">${esc(JSON.stringify({before:r.before_data,after:r.after_data},null,2))}</pre></details></td></tr>`).join('')}</tbody></table></div>`;}

function download(name,type,body){const blob=new Blob([body],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function bind(){const form=document.querySelector('#audit-search');form.addEventListener('submit',async(event)=>{event.preventDefault();try{currentRows=await table('admin_audit_log',queryFor(form));render();}catch(error){show(error.message,'error');}});document.querySelector('#audit-csv').addEventListener('click',()=>{if(!currentRows.length)return show('No hay datos para exportar','error');download(`magina-admin-audit-${new Date().toISOString().slice(0,10)}.csv`,'text/csv;charset=utf-8',toCsv(currentRows));});document.querySelector('#audit-json').addEventListener('click',()=>{if(!currentRows.length)return show('No hay datos para exportar','error');download(`magina-admin-audit-${new Date().toISOString().slice(0,10)}.json`,'application/json',JSON.stringify(currentRows,null,2));});form.requestSubmit();}

function decorate(){const main=document.querySelector('.main');if(!main||document.querySelector('.login-wrap'))return;const section=(location.hash||'#dashboard').slice(1);if(section!=='audit'||main.dataset.auditTool==='true')return;main.dataset.auditTool='true';main.insertAdjacentHTML('beforeend',shell());bind();}
new MutationObserver(()=>queueMicrotask(decorate)).observe(app,{childList:true,subtree:true});addEventListener('hashchange',()=>queueMicrotask(decorate));queueMicrotask(decorate);
