import { insert, patch, rpc, table } from './src/core/api.mjs';

const app=document.querySelector('#app');

function esc(value){return String(value??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function show(text,type='success'){const target=document.querySelector('#flash');if(target)target.innerHTML=`<p class="${type}">${esc(text)}</p>`;}

function shell(){return `<section class="card chat-admin-tool"><div class="section-heading"><div><h2>Chat público de Comunidad</h2><p class="muted">Gestiona canales públicos y modera mensajes reportados. Las conversaciones privadas no forman parte de este panel.</p></div></div><div class="split"><form id="chat-channel-create" class="form"><div class="field"><label>Nombre del canal</label><input name="name" required placeholder="General · Bedmar"></div><div class="field"><label>Slug</label><input name="slug" required placeholder="general-bedmar"></div><div class="field"><label>Descripción</label><textarea name="description"></textarea></div><div class="field"><label>Ruta UUID (opcional)</label><input name="route_id"></div><div class="field"><label>Municipio UUID (opcional)</label><input name="municipality_id"></div><button class="btn primary">Crear canal</button></form><div><h3>Moderación rápida</h3><form id="chat-message-moderate" class="form"><div class="field"><label>Mensaje UUID</label><input name="message_id" required></div><div class="field"><label>Acción</label><select name="action"><option value="hide">Ocultar</option><option value="restore">Restaurar</option><option value="delete">Eliminar</option></select></div><div class="field"><label>Motivo</label><textarea name="reason"></textarea></div><button class="btn secondary">Aplicar</button></form></div></div><div id="chat-admin-data"></div></section>`;}

function rows(rows,headers,mapper){if(!rows.length)return '<p class="muted">Sin datos.</p>';return `<div class="table-wrap"><table class="table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(mapper).join('')}</tbody></table></div>`;}

async function load(){const target=document.querySelector('#chat-admin-data');if(!target)return;try{const [channels,messages,reports]=await Promise.all([
  table('community_chat_channels','?select=id,slug,name,active,route_id,municipality_id,created_at&order=created_at.desc'),
  table('community_chat_messages','?select=id,channel_id,user_id,body,status,created_at,moderation_reason&order=created_at.desc&limit=50'),
  table('community_chat_reports','?select=id,message_id,reporter_user_id,reason,status,created_at&order=created_at.desc&limit=50')
]);target.innerHTML=`<div class="chat-admin-sections"><section><h3>Canales</h3>${rows(channels,['Nombre','Slug','Estado','Ámbito','Acción'],r=>`<tr><td>${esc(r.name)}</td><td class="code">${esc(r.slug)}</td><td>${r.active?'Activo':'Inactivo'}</td><td class="code">${esc(r.route_id||r.municipality_id||'Global')}</td><td><button class="btn tiny secondary" data-channel-id="${esc(r.id)}" data-channel-active="${r.active?'true':'false'}">${r.active?'Desactivar':'Activar'}</button></td></tr>`)}</section><section><h3>Últimos mensajes</h3>${rows(messages,['Mensaje','Usuario','Estado','Texto','Acción'],r=>`<tr><td class="code">${esc(r.id)}</td><td class="code">${esc(r.user_id)}</td><td>${esc(r.status)}</td><td>${esc(r.body)}</td><td><button class="btn tiny danger" data-message-hide="${esc(r.id)}">Ocultar</button></td></tr>`)}</section><section><h3>Reportes</h3>${rows(reports,['Reporte','Mensaje','Motivo','Estado','Acción'],r=>`<tr><td class="code">${esc(r.id)}</td><td class="code">${esc(r.message_id)}</td><td>${esc(r.reason)}</td><td>${esc(r.status)}</td><td>${r.status==='open'?`<button class="btn tiny secondary" data-report-resolve="${esc(r.id)}">Resolver</button>`:''}</td></tr>`)}</section></div>`;

  target.querySelectorAll('[data-channel-id]').forEach(btn=>btn.addEventListener('click',async()=>{try{await patch('community_chat_channels',`id=eq.${encodeURIComponent(btn.dataset.channelId)}`,{active:btn.dataset.channelActive!=='true'});show('Canal actualizado');await load();}catch(error){show(error.message,'error');}}));
  target.querySelectorAll('[data-message-hide]').forEach(btn=>btn.addEventListener('click',async()=>{try{const reason=prompt('Motivo de moderación')||'';if(reason.trim().length<3)return;await rpc('admin_moderate_chat_message',{message_id:btn.dataset.messageHide,action:'hide',reason});show('Mensaje ocultado');await load();}catch(error){show(error.message,'error');}}));
  target.querySelectorAll('[data-report-resolve]').forEach(btn=>btn.addEventListener('click',async()=>{try{const resolution=prompt('Resolución del reporte')||'Revisado por moderación';await rpc('admin_resolve_chat_report',{report_id:btn.dataset.reportResolve,new_status:'resolved',resolution});show('Reporte resuelto');await load();}catch(error){show(error.message,'error');}}));
}catch(error){target.innerHTML=`<p class="error">${esc(error.message)}</p>`;}}

function bind(){const create=document.querySelector('#chat-channel-create');if(create)create.addEventListener('submit',async(event)=>{event.preventDefault();const form=event.currentTarget;try{await insert('community_chat_channels',{name:form.elements.name.value.trim(),slug:form.elements.slug.value.trim(),description:form.elements.description.value.trim(),route_id:form.elements.route_id.value.trim()||null,municipality_id:form.elements.municipality_id.value.trim()||null,active:true});show('Canal creado');form.reset();await load();}catch(error){show(error.message,'error');}});
const mod=document.querySelector('#chat-message-moderate');if(mod)mod.addEventListener('submit',async(event)=>{event.preventDefault();const form=event.currentTarget;try{await rpc('admin_moderate_chat_message',{message_id:form.elements.message_id.value.trim(),action:form.elements.action.value,reason:form.elements.reason.value.trim()});show('Moderación aplicada');form.reset();await load();}catch(error){show(error.message,'error');}});}

async function decorate(){const main=document.querySelector('.main');if(!main||document.querySelector('.login-wrap'))return;const section=(location.hash||'#dashboard').slice(1);if(section!=='community'||main.dataset.chatTool==='true')return;main.dataset.chatTool='true';main.insertAdjacentHTML('beforeend',shell());bind();await load();}

new MutationObserver(()=>queueMicrotask(decorate)).observe(app,{childList:true,subtree:true});
addEventListener('hashchange',()=>queueMicrotask(decorate));
queueMicrotask(decorate);
