import { insert, patch, table } from './src/core/api.mjs';

const app=document.querySelector('#app');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function show(t,type='success'){const e=document.querySelector('#flash');if(e)e.innerHTML=`<p class="${type}">${esc(t)}</p>`;}
function f(name,label,type='text',extra=''){return `<div class="field"><label>${esc(label)}</label><input name="${esc(name)}" type="${esc(type)}" ${extra}></div>`;}

function shell(){return `<section class="card gamification-catalog-tool"><h2>Retos, temporadas y colecciones</h2><div class="gamification-admin-grid"><form id="challenge-create" class="form"><h3>Nuevo reto</h3>${f('title','Título','text','required')}<div class="field"><label>Descripción</label><textarea name="description" required></textarea></div>${f('starts_at','Inicio','datetime-local','required')}${f('ends_at','Fin','datetime-local','required')}${f('reward_xp','XP','number','min="0" value="0"')}${f('reward_olives','Aceitunas','number','min="0" value="0"')}<button class="btn primary">Crear reto</button></form><form id="season-create" class="form"><h3>Nueva temporada</h3>${f('slug','Slug','text','required')}${f('name','Nombre','text','required')}<div class="field"><label>Descripción</label><textarea name="description"></textarea></div>${f('starts_at','Inicio','datetime-local','required')}${f('ends_at','Fin','datetime-local','required')}${f('xp_multiplier','Multiplicador XP','number','min="0.1" step="0.1" value="1"')}${f('olive_multiplier','Multiplicador aceitunas','number','min="0.1" step="0.1" value="1"')}<button class="btn secondary">Crear temporada</button></form><form id="collection-create" class="form"><h3>Nueva colección</h3>${f('slug','Slug','text','required')}${f('name','Nombre','text','required')}<div class="field"><label>Descripción</label><textarea name="description"></textarea></div>${f('reward_xp','XP por completar','number','min="0" value="0"')}${f('reward_olives','Aceitunas por completar','number','min="0" value="0"')}<button class="btn secondary">Crear colección</button></form><form id="collection-item-create" class="form"><h3>Añadir descubrimiento</h3>${f('collection_id','Colección UUID','text','required')}${f('discovery_id','Descubrimiento UUID','text','required')}${f('sort_order','Orden','number','value="0"')}<button class="btn secondary">Vincular</button></form></div><div id="gamification-catalog-list"></div></section>`;}

function simpleTable(title,rows,cols){return `<section><h3>${esc(title)} (${rows.length})</h3>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}<th></th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c[1]])}</td>`).join('')}<td>${'active' in r?`<button class="btn tiny secondary" data-toggle-table="${esc(title)}" data-id="${esc(r.id)}" data-active="${r.active?'true':'false'}">${r.active?'Desactivar':'Activar'}</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Sin datos.</p>'}</section>`;}

async function load(){const target=document.querySelector('#gamification-catalog-list');if(!target)return;try{const [challenges,seasons,collections]=await Promise.all([table('gamification_challenges','?select=id,title,starts_at,ends_at,reward_xp,reward_olives,active&order=starts_at.desc'),table('gamification_seasons','?select=id,slug,name,starts_at,ends_at,xp_multiplier,olive_multiplier,active&order=starts_at.desc'),table('discovery_collections','?select=id,slug,name,reward_xp,reward_olives,active&order=name.asc')]);target.innerHTML=`<div class="gamification-lists">${simpleTable('Retos',challenges,[['Título','title'],['Inicio','starts_at'],['Fin','ends_at'],['XP','reward_xp'],['Aceitunas','reward_olives']])}${simpleTable('Temporadas',seasons,[['Nombre','name'],['Inicio','starts_at'],['Fin','ends_at'],['xXP','xp_multiplier'],['xAceitunas','olive_multiplier']])}${simpleTable('Colecciones',collections,[['Nombre','name'],['Slug','slug'],['XP','reward_xp'],['Aceitunas','reward_olives']])}</div>`;target.querySelectorAll('[data-toggle-table]').forEach(btn=>btn.addEventListener('click',async()=>{const map={Retos:'gamification_challenges',Temporadas:'gamification_seasons',Colecciones:'discovery_collections'};try{await patch(map[btn.dataset.toggleTable],`id=eq.${encodeURIComponent(btn.dataset.id)}`,{active:btn.dataset.active!=='true'});show('Estado actualizado');await load();}catch(error){show(error.message,'error');}}));}catch(error){target.innerHTML=`<p class="error">${esc(error.message)}</p>`;}}

function bindForm(id,handler){const form=document.querySelector(`#${id}`);if(!form)return;form.addEventListener('submit',async(event)=>{event.preventDefault();try{await handler(form);show('Guardado');form.reset();await load();}catch(error){show(error.message,'error');}});}
function iso(value){const d=new Date(value);if(Number.isNaN(d.valueOf()))throw new Error('Fecha no válida');return d.toISOString();}
function bind(){bindForm('challenge-create',f=>insert('gamification_challenges',{title:f.elements.title.value.trim(),description:f.elements.description.value.trim(),starts_at:iso(f.elements.starts_at.value),ends_at:iso(f.elements.ends_at.value),reward_xp:Number(f.elements.reward_xp.value||0),reward_olives:Number(f.elements.reward_olives.value||0),active:true}));bindForm('season-create',f=>insert('gamification_seasons',{slug:f.elements.slug.value.trim(),name:f.elements.name.value.trim(),description:f.elements.description.value.trim(),starts_at:iso(f.elements.starts_at.value),ends_at:iso(f.elements.ends_at.value),xp_multiplier:Number(f.elements.xp_multiplier.value||1),olive_multiplier:Number(f.elements.olive_multiplier.value||1),active:true}));bindForm('collection-create',f=>insert('discovery_collections',{slug:f.elements.slug.value.trim(),name:f.elements.name.value.trim(),description:f.elements.description.value.trim(),reward_xp:Number(f.elements.reward_xp.value||0),reward_olives:Number(f.elements.reward_olives.value||0),active:true}));bindForm('collection-item-create',f=>insert('discovery_collection_items',{collection_id:f.elements.collection_id.value.trim(),discovery_id:f.elements.discovery_id.value.trim(),sort_order:Number(f.elements.sort_order.value||0)}));}

async function decorate(){const main=document.querySelector('.main');if(!main||document.querySelector('.login-wrap'))return;const section=(location.hash||'#dashboard').slice(1);if(section!=='gamification'||main.dataset.gamificationCatalog==='true')return;main.dataset.gamificationCatalog='true';main.insertAdjacentHTML('beforeend',shell());bind();await load();}
new MutationObserver(()=>queueMicrotask(decorate)).observe(app,{childList:true,subtree:true});
addEventListener('hashchange',()=>queueMicrotask(decorate));
queueMicrotask(decorate);
