import { patch, table } from './src/core/api.mjs';
import { normalizeMediaTags } from './src/core/media.mjs';

const app=document.querySelector('#app');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function show(t,type='success'){const e=document.querySelector('#flash');if(e)e.innerHTML=`<p class="${type}">${esc(t)}</p>`;}

function shell(){return `<section class="card media-manager-tool"><h2>Gestión de imágenes y archivos</h2><p class="muted">Edita metadatos, accesibilidad, etiquetas y estado de archivo sin borrar físicamente contenido aún referenciado por rutas.</p><form id="media-edit" class="form two"><div class="field"><label>Media UUID</label><input name="id" required></div><div class="field"><label>Título</label><input name="title" required></div><div class="field span-2"><label>Texto alternativo</label><input name="alt_text"></div><div class="field span-2"><label>Etiquetas (coma)</label><input name="tags" placeholder="ruta, patrimonio, olivar"></div><div class="field"><label>Estado</label><select name="archived"><option value="false">Activo</option><option value="true">Archivado</option></select></div><button class="btn primary">Guardar metadatos</button></form><div id="media-manager-list"></div></section>`;}

async function load(){const target=document.querySelector('#media-manager-list');if(!target)return;try{const rows=await table('media_assets','?select=id,title,alt_text,mime_type,byte_size,tags,archived,created_at&order=created_at.desc&limit=100');target.innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Título</th><th>Tipo</th><th>Etiquetas</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.title)}<br><span class="code">${esc(r.id)}</span></td><td>${esc(r.mime_type)}</td><td>${esc((r.tags||[]).join(', '))}</td><td>${r.archived?'Archivado':'Activo'}</td><td><button class="btn tiny secondary" data-media-edit="${esc(r.id)}">Editar</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Sin archivos.</p>';target.querySelectorAll('[data-media-edit]').forEach(btn=>btn.addEventListener('click',()=>{const r=rows.find(x=>x.id===btn.dataset.mediaEdit);const f=document.querySelector('#media-edit');f.elements.id.value=r.id;f.elements.title.value=r.title||'';f.elements.alt_text.value=r.alt_text||'';f.elements.tags.value=(r.tags||[]).join(', ');f.elements.archived.value=String(Boolean(r.archived));f.elements.title.focus();}));}catch(error){target.innerHTML=`<p class="error">${esc(error.message)}</p>`;}}

function bind(){const form=document.querySelector('#media-edit');if(!form)return;form.addEventListener('submit',async(event)=>{event.preventDefault();try{await patch('media_assets',`id=eq.${encodeURIComponent(form.elements.id.value.trim())}`,{title:form.elements.title.value.trim(),alt_text:form.elements.alt_text.value.trim()||null,tags:normalizeMediaTags(form.elements.tags.value),archived:form.elements.archived.value==='true'});show('Metadatos actualizados');form.reset();await load();}catch(error){show(error.message,'error');}});}

async function decorate(){const main=document.querySelector('.main');if(!main||document.querySelector('.login-wrap'))return;const section=(location.hash||'#dashboard').slice(1);if(section!=='media'||main.dataset.mediaManager==='true')return;main.dataset.mediaManager='true';main.insertAdjacentHTML('beforeend',shell());bind();await load();}
new MutationObserver(()=>queueMicrotask(decorate)).observe(app,{childList:true,subtree:true});addEventListener('hashchange',()=>queueMicrotask(decorate));queueMicrotask(decorate);
