import { insert, table } from './src/core/api.mjs';

const app=document.querySelector('#app');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function show(t,type='success'){const e=document.querySelector('#flash');if(e)e.innerHTML=`<p class="${type}">${esc(t)}</p>`;}

function explain(audience){return audience==='all'?'Se enviará a todos los dispositivos activos.':audience==='route'?'Indica el UUID de la ruta. Solo recibirán el aviso quienes sigan esa ruta.':audience==='municipality'?'Indica el UUID del municipio.':audience==='role'?'Indica el rol administrativo: super_admin, admin, route_manager, moderator o partner.':'';}

function enhanceCreateForm(){const form=document.querySelector('#notification-create');if(!form||form.dataset.segmented==='true')return;form.dataset.segmented='true';const button=form.querySelector('button[type="submit"],button');button?.insertAdjacentHTML('beforebegin',`<div class="field"><label>Referencia de audiencia</label><input name="audience_ref" placeholder="UUID o rol"><small id="notification-audience-help" class="muted"></small></div>`);const audience=form.elements.audience;const update=()=>{const input=form.elements.audience_ref;const all=audience.value==='all';input.disabled=all;input.required=!all;if(all)input.value='';document.querySelector('#notification-audience-help').textContent=explain(audience.value);};audience.addEventListener('change',update);update();
form.addEventListener('submit',async(event)=>{event.preventDefault();event.stopImmediatePropagation();const ref=form.elements.audience_ref.value.trim();if(audience.value!=='all'&&!ref)return show('Indica la referencia de audiencia','error');try{await insert('admin_notifications',{title:form.elements.title.value.trim(),body:form.elements.body.value.trim(),audience:audience.value,audience_ref:ref||null,status:'draft'});show('Notificación guardada como borrador');form.reset();update();setTimeout(()=>location.reload(),250);}catch(error){show(error.message,'error');}},true);}

function statusCard(label,value){return `<div class="card kpi"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;}
async function deliveryPanel(){if(document.querySelector('#notification-delivery-panel'))return;const main=document.querySelector('.main');if(!main)return;const panel=document.createElement('section');panel.id='notification-delivery-panel';panel.className='card';panel.innerHTML='<h2>Estado de entregas</h2><p class="muted">Cargando cola…</p>';main.append(panel);try{const rows=await table('notification_deliveries','?select=status,notification_id,created_at,sent_at&order=created_at.desc&limit=500');const counts={pending:0,processing:0,sent:0,failed:0,skipped:0};for(const row of rows)counts[row.status]=(counts[row.status]||0)+1;panel.innerHTML=`<h2>Estado de entregas</h2><div class="grid kpis">${statusCard('Pendientes',counts.pending)}${statusCard('Procesando',counts.processing)}${statusCard('Enviadas',counts.sent)}${statusCard('Fallidas',counts.failed)}</div><p class="muted">La cola está preparada para segmentar por todos, ruta, municipio o rol. Los tokens de dispositivo no se muestran en el panel.</p>`;}catch(error){panel.innerHTML=`<h2>Estado de entregas</h2><p class="error">${esc(error.message)}</p>`;}}

function decorate(){const main=document.querySelector('.main');if(!main||document.querySelector('.login-wrap'))return;const section=(location.hash||'#dashboard').slice(1);if(section!=='notifications')return;enhanceCreateForm();deliveryPanel();}
new MutationObserver(()=>queueMicrotask(decorate)).observe(app,{childList:true,subtree:true});addEventListener('hashchange',()=>queueMicrotask(decorate));queueMicrotask(decorate);
