import { patch, table } from './src/core/api.mjs';

const app=document.querySelector('#app');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function show(t,type='success'){const e=document.querySelector('#flash');if(e)e.innerHTML=`<p class="${type}">${esc(t)}</p>`;}
function localValue(value){if(!value)return '';const d=new Date(value);const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`;}
function isoOrNull(value){return value?new Date(value).toISOString():null;}

function shell(){return `<section class="card reward-manager-tool"><h2>Política de premios</h2><p class="muted">Gestiona límites por usuario, validez y disponibilidad. El tiempo de reserva del QR se controla desde Configuración.</p><form id="reward-edit" class="form two"><div class="field"><label>Premio UUID</label><input name="id" required></div><div class="field"><label>Partner UUID</label><input name="partner_id" required></div><div class="field"><label>Título</label><input name="title" required></div><div class="field"><label>Coste aceitunas</label><input name="olive_cost" type="number" min="1" required></div><div class="field"><label>Stock</label><input name="stock" type="number" min="0" required></div><div class="field"><label>Límite por usuario</label><input name="per_user_limit" type="number" min="1" required></div><div class="field"><label>Válido desde</label><input name="valid_from" type="datetime-local" required></div><div class="field"><label>Válido hasta (opcional)</label><input name="valid_until" type="datetime-local"></div><div class="field span-2"><label>Descripción</label><textarea name="description"></textarea></div><div class="field"><label>Estado</label><select name="active"><option value="true">Activo</option><option value="false">Inactivo</option></select></div><button class="btn primary">Guardar premio</button></form><div id="reward-manager-list"></div></section>`;}

async function load(){const target=document.querySelector('#reward-manager-list');if(!target)return;try{const rows=await table('rewards','?select=id,partner_id,title,description,olive_cost,stock,per_user_limit,valid_from,valid_until,active,updated_at&order=updated_at.desc&limit=100');target.innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Premio</th><th>Coste</th><th>Stock</th><th>Límite</th><th>Validez</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.title)}<br><span class="code">${esc(r.id)}</span></td><td>${esc(r.olive_cost)}</td><td>${esc(r.stock)}</td><td>${esc(r.per_user_limit)}</td><td>${esc(r.valid_from)}<br>${r.valid_until?esc(r.valid_until):'Sin fin'}<br>${r.active?'Activo':'Inactivo'}</td><td><button class="btn tiny secondary" data-reward-edit="${esc(r.id)}">Editar</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Sin premios.</p>';target.querySelectorAll('[data-reward-edit]').forEach(btn=>btn.addEventListener('click',()=>{const r=rows.find(x=>x.id===btn.dataset.rewardEdit);const f=document.querySelector('#reward-edit');for(const k of ['id','partner_id','title','olive_cost','stock','per_user_limit','description'])f.elements[k].value=r[k]??'';f.elements.valid_from.value=localValue(r.valid_from);f.elements.valid_until.value=localValue(r.valid_until);f.elements.active.value=String(Boolean(r.active));f.elements.title.focus();}));}catch(error){target.innerHTML=`<p class="error">${esc(error.message)}</p>`;}}

function bind(){const form=document.querySelector('#reward-edit');if(!form)return;form.addEventListener('submit',async(event)=>{event.preventDefault();try{await patch('rewards',`id=eq.${encodeURIComponent(form.elements.id.value.trim())}`,{partner_id:form.elements.partner_id.value.trim(),title:form.elements.title.value.trim(),description:form.elements.description.value.trim(),olive_cost:Number(form.elements.olive_cost.value),stock:Number(form.elements.stock.value),per_user_limit:Number(form.elements.per_user_limit.value),valid_from:isoOrNull(form.elements.valid_from.value),valid_until:isoOrNull(form.elements.valid_until.value),active:form.elements.active.value==='true',updated_at:new Date().toISOString()});show('Premio actualizado');form.reset();await load();}catch(error){show(error.message,'error');}});}

async function decorate(){const main=document.querySelector('.main');if(!main||document.querySelector('.login-wrap'))return;const section=(location.hash||'#dashboard').slice(1);if(section!=='rewards'||main.dataset.rewardManager==='true')return;main.dataset.rewardManager='true';main.insertAdjacentHTML('beforeend',shell());bind();await load();}
new MutationObserver(()=>queueMicrotask(decorate)).observe(app,{childList:true,subtree:true});addEventListener('hashchange',()=>queueMicrotask(decorate));queueMicrotask(decorate);
