import { insert, rpc, table } from './src/core/api.mjs';

const app=document.querySelector('#app');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function show(text,type='success'){const target=document.querySelector('#flash');if(target)target.innerHTML=`<p class="${type}">${esc(text)}</p>`;}

function shell(){return `<section class="card safety-gate-tool"><h2>Cierre temporal de ruta</h2><p class="muted">Bloquea el inicio de nuevas aventuras sin archivar la ruta. Al resolver la incidencia, la ruta vuelve a quedar disponible automáticamente.</p><form id="route-closure-create" class="form two"><div class="field"><label>Ruta UUID</label><input name="route_id" required></div><div class="field"><label>Título</label><input name="title" value="Ruta temporalmente cerrada" required></div><div class="field"><label>Severidad</label><select name="severity"><option value="warning">warning</option><option value="critical" selected>critical</option></select></div><div class="field"><label>Fin previsto (opcional)</label><input name="ends_at" type="datetime-local"></div><div class="field span-2"><label>Motivo / indicaciones</label><textarea name="description" required></textarea></div><button class="btn danger span-2">Bloquear inicio de aventuras</button></form><div id="active-route-closures"></div></section>`;}

async function load(){const target=document.querySelector('#active-route-closures');if(!target)return;try{const rows=await table('route_safety_incidents','?select=id,route_id,title,severity,starts_at,ends_at&status=eq.open&blocks_adventure=eq.true&order=starts_at.desc&limit=100');target.innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Ruta</th><th>Incidencia</th><th>Severidad</th><th>Desde</th><th>Hasta</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td class="code">${esc(r.route_id)}</td><td>${esc(r.title)}</td><td>${esc(r.severity)}</td><td>${esc(r.starts_at)}</td><td>${esc(r.ends_at||'Sin fecha')}</td><td><button class="btn tiny secondary" data-reopen="${esc(r.id)}">Reabrir ruta</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">No hay cierres temporales activos.</p>';target.querySelectorAll('[data-reopen]').forEach(button=>button.addEventListener('click',async()=>{try{await rpc('admin_resolve_safety',{incident_id:button.dataset.reopen});show('Ruta reabierta: incidencia resuelta');await load();}catch(error){show(error.message,'error');}}));}catch(error){target.innerHTML=`<p class="error">${esc(error.message)}</p>`;}}

function bind(){const form=document.querySelector('#route-closure-create');if(!form)return;form.addEventListener('submit',async(event)=>{event.preventDefault();try{const d=Object.fromEntries(new FormData(form).entries());await insert('route_safety_incidents',{route_id:d.route_id.trim(),title:d.title.trim(),description:d.description.trim(),severity:d.severity,status:'open',blocks_adventure:true,starts_at:new Date().toISOString(),ends_at:d.ends_at?new Date(d.ends_at).toISOString():null});show('Ruta cerrada temporalmente para nuevas aventuras');form.reset();await load();}catch(error){show(error.message,'error');}});}

async function decorate(){const main=document.querySelector('.main');if(!main||document.querySelector('.login-wrap'))return;const section=(location.hash||'#dashboard').slice(1);if(section!=='safety'||main.dataset.safetyGate==='true')return;main.dataset.safetyGate='true';main.insertAdjacentHTML('beforeend',shell());bind();await load();}
new MutationObserver(()=>queueMicrotask(decorate)).observe(app,{childList:true,subtree:true});addEventListener('hashchange',()=>queueMicrotask(decorate));queueMicrotask(decorate);
